# Generated by Django 3.2.2 on 2021-05-18 15:13

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True,
                 max_length=255, verbose_name='サイト名')),
                ('dataset_url', models.URLField()),
                ('ckanapi_url', models.URLField()),
                ('proxy_url', models.URLField()),
                ('is_fq_available', models.BooleanField(
                    default=True, verbose_name='is_fq_available')),
                ('update_interval', models.CharField(max_length=255, null=True, validators=[
                 sites.models.validate_interval], verbose_name='update-interval')),
                ('full_update_interval', models.CharField(max_length=255, null=True, validators=[
                 sites.models.validate_interval], verbose_name='full-update-interval')),
                ('contact', models.CharField(max_length=255, null=True)),
                ('result', models.BooleanField(default=True, verbose_name='前回結果')),
                ('executed_at', models.DateTimeField(
                    null=True, verbose_name='前回実行時間')),
                ('full_result', models.BooleanField(
                    default=True, verbose_name='前回結果(FULL)')),
                ('full_executed_at', models.DateTimeField(
                    null=True, verbose_name='前回実行時間(FULL)')),
                ('enable', models.BooleanField(default=True, verbose_name='有効/無効')),
            ],
            options={
                'verbose_name_plural': 'Ckanサイト',
                'db_table': 'sites_site',
            },
        ),
    ]
