# Generated by Django 3.2.2 on 2021-06-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_add_publisher_to_your_site_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='full_update_start_datetime',
            field=models.DateTimeField(null=True, verbose_name='実行開始時間(FULL)'),
        ),
        migrations.AddField(
            model_name='site',
            name='full_update_time',
            field=models.DateTimeField(null=True, verbose_name='実行予定時間(FULL)'),
        ),
        migrations.AddField(
            model_name='site',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='実行予定時間'),
        ),
        migrations.AddField(
            model_name='site',
            name='update_start_datetime',
            field=models.DateTimeField(null=True, verbose_name='実行開始時間'),
        ),
    ]
