# Generated by Django 3.2.5 on 2021-07-02 12:46

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_modify_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name_plural': 'CKANサイト'},
        ),
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='executed_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='前回更新実行日時'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_executed_at',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='前回完全更新実行日時'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_result',
            field=models.BooleanField(
                blank=True, default=True, verbose_name='前回完全更新結果'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_update_interval',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[
                                   sites.models.validate_interval], verbose_name='完全更新間隔'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_update_start_datetime',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='完全更新開始日時'),
        ),
        migrations.AlterField(
            model_name='site',
            name='full_update_time',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='完全更新実行予定日時'),
        ),
        migrations.AlterField(
            model_name='site',
            name='proxy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='publisher_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='result',
            field=models.BooleanField(
                blank=True, default=True, verbose_name='前回更新結果'),
        ),
        migrations.AlterField(
            model_name='site',
            name='update_interval',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[
                                   sites.models.validate_interval], verbose_name='更新間隔'),
        ),
        migrations.AlterField(
            model_name='site',
            name='update_start_datetime',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='更新開始日時'),
        ),
        migrations.AlterField(
            model_name='site',
            name='update_time',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='更新実行予定日時'),
        ),
    ]
