# Generated by Django 3.2.12 on 2023-03-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_add_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='tag_default',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='デフォルトタグ'),
        ),
        migrations.AddField(
            model_name='site',
            name='tag_vocabulary',
            field=models.TextField(blank=True, null=True, verbose_name='タグ用統制語彙'),
        ),
    ]
