# Generated by Django 3.2.12 on 2023-03-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_add_tag_vocabulary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='ckanapi_url',
            field=models.URLField(verbose_name='API URL'),
        ),
    ]
